= tools.build Reference
Alex Miller
2020-06-29
:type: reference
:toc: macro

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Terms

* Basis - given a chain of deps.edn files and modifiers to resolve-deps, make-classpath, etc, the tools.deps library will produce a "runtime basis" consisting of the library and classpath execution environment and alias data
* Build - a build invocation loads a project basis and runs an ordered series of build tasks to create one or more artifacts
* Task - a build step, invoked with the basis, and a combination of shared parameters, task parameters, and flow parameters. Tasks may produce side effects (often writing to disk) and return new flow parameters that can be used by later tasks.
* Shared parameter - attribute provided to all tasks (ignored if not used by a task)
* Task parameter - attribute provided only to a single task, will override any shared parameter
* Project directory - the directory containing deps.edn and all other project source files
* Output directory - the output directory, defaults to the same as `<project-dir>`

== tools.build API

The primary function for executing a build is:

[source,clojure]
----
clojure.tools.build/build
([{:keys [project-dir output-dir tasks params verbose]}])
  Executes a project build consisting of tasks using shared parameters.

    :project-dir (optional) - path to project root, should include deps.edn file (default = current directory),
                              used to form the project basis
    :output-dir (optional) - path to output root (default = project-dir)
    :tasks (required) - coll of task steps in the form [task-sym task-params]
                        task-sym (required) - unqualified for built-in tasks, otherwise should resolve to a var
                        task-params (optional) - map of parameters overriding shared params
    :params (optional) - shared params passed to all tasks or an alias referring to them

   Build steps:
     Load basis from project-dir
     Load build params from either a map or an alias
     Run tasks, each task is passed the basis and a merge of build params and task-specific params
     Output files and dirs relative to output-dir
----

== Shared directories and params

Many parameters are shared across multiple tasks - this is important both to reduce the number of parameters to set and to allow tasks to work together. All parameters should be qualified. Namespace of `build` is reserved.

Important directory parameters shared across the built-in tasks:

[options="header", role="table"]
|===
| Directory parameter | Description
| `:build/project-dir` | The project directory specified in the build, should contain `deps.edn` and serve as the root for all input directories, defaults to current directory.
| `:build/output-dir` | The output directory, root for all output, defaults to project directory.
| `:build/target-dir` | The target directory, designed to write new outputs or as a working area. Interpreted relative to `:build/output-dir`.
| `:build/class-dir` | The classes directory, which is the default output for compilation tasks and resources and the default directory to use when creating a jar file. Intepreted relative to `:build/output-dir`, such as `"target/classes"`.
| `:build/pom-dir` | The pom directory is where the pom.xml and pom.properties are created, following Maven coventions for jar construction. Interpreted relative to `:build/output-dir`.
| `:build/clj-paths` | Coll of directories that are Clojure source roots, resolved relative to `:build/project-dir`. See `clj-compile` task.
| `:build/java-paths` | Coll of directories that are Java source roots, resolved relative to `:build/project-dir`. See `javac` task.
|===

The `dirs` task can be used to initialize most of these according to common Maven conventions.

Additionally, there are some project-oriented parameters that are shared across tasks:

[options="header", role="table"]
|===
| Shared parameter | Description
| `:build/lib` | Qualified symbol defining this projects lib name (in Maven terms `groupId/artifactId`)
| `:build/classifier` | String specifying the library classifier
| `:build/version` | String representing this project's version number
| `:build/main-class` | Symbol for the Clojure namespace with a -main or Java main class
|===

== Built-in tasks

The following built-in tasks are provided (these may all be specified unqualified):

[options="header", role="table"]
|===
| Task | Description
| `dirs` | Create directory params matching Maven build conventions
| `clean` | Clean target dir
| `compile-clj` | Compile Clojure namespaces to classes
| `sync-pom` | Use base pom.xml and deps.edn to produce an output pom.xml
| `javac` | Compile Java source to classes
| `copy` | Copy source and resource files to classes (w/string replacement)
| `jar` | Create a jar containing classes etc
| `uber` | Create an uberjar containing the jar and all dependent jars
| `zip` | Zip output files
| `process` | Execute an external process
| `format-str` | Format a string template with param replacement
| `install` | Install the created jar to local Maven cache
|===

=== dirs task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/lib` | yes | Qualified symbol defining this projects lib name (in Maven terms `groupId/artifactId`)
| `:build/version` | yes | String representing this project's version number
| `:build/classifier` | | String specifying the library classifier
|===

Constructs and returns a set of default directories and other Maven-convention build params:

[options="header", role="table"]
|===
| Output param | Description
| `:build/target-dir` | `"target"` - target dir for making outputs and intermediate products
| `:build/class-dir` | `"target/classes"` - building jar structure (compiled outputs, resources)
| `:build/pom-dir` | `"target/classes/META-INF/maven/group-id/artifact-id"` - Maven place to put pom
| `:build/jar-file` | `"target/artifact-id-[classifier-]version.jar"` - jar artifact
| `:build/uber-file` | `"target/artifact-id-[classifier-]version-standalone.jar"` - uberjar artifact
|===

=== clean task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/target-dir` | yes | Target dir, relative to `:build/output-dir`
|===

Removes the target dir recursively.

=== compile-clj task

[options="header", role="table"]
|===
| Basis key | Description
| `:classpath` | Classpath data from basis
|===

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/project-dir` | yes | Project dir
| `:build/output-dir` | yes | Output dir
| `:build/target-dir` | yes | Target dir, relative to `:build/output-dir`
| `:build/class-dir` | yes | Class output dir, relative to `:build/output-dir`
| `:build/clj-paths` | | Coll of Clojure source roots
| `:build/compiler-opts` | | Map of https://clojure.org/reference/compilation#_compiler_options[compiler options]
| `:build/ns-compile` | | Coll of namespace symbols
| `:build/filter-nses` | | Coll of namespace symbol roots
|===

The `compile-clj` task compiles either an explicit list of namespaces in `:build/ns-compile` or all namespaces detected in `:build/clj-paths` (one of these is required). Namespaces are compiled with `:build/compiler-opts` if provided and output to intermediate `output-dir/target-dir/compile-clj` then filtered with `:build/filter-nses` (coll of namespace prefix symbols) into `output-dir/class-dir`.

Compilation occurs in a forked process using the `:classpath` from the computed project basis. Compilation errors will be printed to stderr and will cause build execution to abort.

Example compiling all Clojure namespaces in Clojure source paths (when making an uberjar for example):

[source,clojure]
----
[compile-clj {:build/project-dir "..."
              :build/target-dir "target"
              :build/class-dir "target/classes"
              :build/clj-paths :clj-paths}]
----

Example compiling specific Clojure namespaces with direct linking and keeping only classes from this library:

[source,clojure]
----
[compile-clj {:build/project-dir "..."
              :build/target-dir "target"
              :build/class-dir "target/classes"
              :build/ns-compile [a.b.c a.b.d]
              :build/compiler-options {:direct-linking true}
              :build/filter-nses [a.b]}]
----

=== javac task

[options="header", role="table"]
|===
| Basis key | Description
| `:libs` | Lib map data from basis
|===

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/project-dir` | yes | Project dir
| `:build/output-dir` | yes | Output dir
| `:build/class-dir` | yes | Class output dir, relative to `:build/output-dir`
| `:build/java-paths` | yes | Coll of Java source roots, relative to `:build/project-dir`
| `:build/javac-opts` | | Coll of Java options to be used with javac
|===

Compile all Java source files under `:build/java-paths` with `:build/javac-opts` into `:build/class-dir`. Compilation occurs in-process. Compilation errors will be printed to stderr and will cause build execution to abort.

Example:

[source,clojure]
----
[javac {:build/project-dir "..."
        :build/target-dir "target"
        :build/class-dir "classes"
        :build/java-paths :java-paths
        :build/javac-opts ["-source" "8" "-target" "8"]}]
----

=== sync-pom task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/project-dir` | yes | Project dir
| `:build/output-dir` | yes | Output dir 
| `:build/pom-dir` | yes | Pom output directory, resolved relative to `:build/output-dir`
| `:build/src-pom` | default="pom.xml"| Source pom file, relative to `build/project-dir`
| `:build/lib` | yes
| `:build/version` | yes
|===

Write pom.xml and pom.properties to `<output-dir>/<pom-dir>`, matching Maven conventions. The `:build/src-pom` is used as a base pom.xml file if it exists, then updated with dependencies, repositories, src dir, maven coordinates, etc based on the params and/or the deps.edn in `:build/project-dir`.

=== copy task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/project-dir` | yes | Project dir
| `:build/output-dir` | yes | Output dir
| `:build/copy-to` | | Directory, relative to `:build/target-dir` to copy to, defaults to `:build/class-dir`
| `:build/copy-specs` | yes | Coll of copy specs specifying what to copy
|===

Each copy spec has the following keys:

[options="header", role="table"]
|===
| Copy spec key | Description
| `:from` | Directory or coll of dirs resolved relative to `:build/project-dir`
| `:include` | File glob or coll of file globs to include
| `:replace` | Map of string replacements to make in this copy, from source text to replacement text (which may also be params)
|===

The copy task copies all files specified by the copy specs to the `copy-to` directory (by default the classes dir), defaults intended for copying resource files (but other uses possible, typically with per-task overrides). The paths relative to `:from` are retained in the copy.

Copying Clojure sources for jar inclusion:

[source,clojure]
----
[copy {:build/project-dir "..."
       :build/target-dir "target"
       :build/class-dir "classes"
       :build/copy-specs [{:from :clj-paths}]}]
----

Copying resources with replacement:

[source,clojure]
----
[copy {:build/project-dir "..."
       :build/target-dir "target"
       :build/class-dir "classes"
       :build/copy-specs [{:from "resources" :replace {"$version" :build/version}}]}]
----

Copying licenses from legal dir:

[source,clojure]
----
[copy {:build/project-dir "..."
       :build/target-dir "target"
       :build/class-dir "classes"
       :build/copy-specs [{:from "legal" :include "**license*"}]}]
----

=== jar task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/output-dir` | yes | Output dir
| `:build/class-dir` | yes | Class assembly dir, resolved relative to `:build/output-dir`
| `:build/jar-file` | yes | Jar file name, resolved relative to `:build/output-dir`
| `:build/main-class` | | Symbol for the Clojure namespace with a -main or Java main class
|===

Create jar file named `jar-file` in `output-dir` containing contents of `class-dir`. Manifest will have `main-class` set.

=== uber task

[options="header", role="table"]
|===
| Basis key | Description
| `:libs` | Lib map data from basis
|===

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/output-dir` | yes | Output dir
| `:build/target-dir` | yes | Target dir
| `:build/class-dir` | yes | Class output dir, resolved relative to `:build/target-dir`
| `:build/uber-file` | yes | Name of output uber jar file, resolved relative to `:build/output-dir`
| `:build/main-class` | | Symbol for the Clojure namespace with a -main or Java main class
|===

Create an uber jar that contains the contents of the `:build/class-dir` and all library dependencies from the basis lib map. Set main-class in the manifest. Assembly occurs in `target-dir/uber` directory.

These resources are filtered (not yet configurable):

* `#"META-INF/.*\.(?:SF|RSA|DSA)"`

In the case of multiple jars with the same resource (not yet configurable):

* data_readers.clj(c) - merge
* anything else - print conflict to stdout

=== zip task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/output-dir` | yes | Output dir
| `:build/zip-dir` | yes | Directory relative to `:build/output-dir` to assemble zip
| `:build/zip-name` | yes | Name of output zip file, relative to `:build/output-dir`
|===

Creates zip file of zip-dir's contents in zip-name.

=== process task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/command` | yes | Coll of process params
| `:build/out>` |  | Flow param key with which to return the process output
|===

Expect the command as specified in command and return the trimmed stdout result in the specified flow param.

Output flow params:

[options="header", role="table"]
|===
| Flow param | Description
| Value of `:build/out>` | Return the trimmed stdout result of executing the command
|===

=== format-str task

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/template` | yes | String template per Java formatter
| `:build/args` | yes | Coll of args (resolved as params) to feed the template
| `:build/out>` | yes | Flow param key with which to return the process output
|===

Format the string template with the args and put the result in the out> flow param.

Output flow params:

[options="header", role="table"]
|===
| Flow param | Description
| Value of `:build/out>` | Return the formatting template
|===

=== install task

* Prereq tasks: expects jar file from `jar` task and pom file from `sync-pom` task

[options="header", role="table"]
|===
| Basis key | Description
| `:mvn/local-repo` | Local repository location (default to ~/.m2/repository)
|===

[options="header", role="table"]
|===
| Parameter | Required? | Description
| `:build/output-dir` | yes | Output dir
| `:build/lib` | yes | Qualified symbol defining this projects lib name (in Maven terms `groupId/artifactId`)
| `:build/classifier` | | String specifying the library classifier
| `:build/version` | yes | String representing this project's version number
| `:flow/pom-dir` | yes | Pom dir containing output pom.xml (see `sync-pom`)
|===

Installs the jar (created by the `jar` task) into the Maven local repository.

== Usage as a deps tool

Add to your deps.edn and add as a tool:

[source,clojure]
----
{...
 :aliases
 {:build
  {:replace-deps {org.clojure/tools.build {:git/url "git@github.com:cognitect-labs/tools.build.git"
                                           :sha "<SHA>"}
                  org.slf4j/slf4j-nop {:mvn/version "1.7.25"}}
   :exec-fn clojure.tools.build/build
   :exec-args {:tasks [[dirs] [clean] [copy] [sync-pom] [jar]]
               :params {:build/copy-specs [{:from :clj-paths}]
                        :build/lib my/lib1
                        :build/version "1.2.3"}}}}}
----

You can find the latest sha for tools.build with:

[source]
----
git ls-remote git@github.com:cognitect-labs/tools.build.git refs/heads/master
----

Run it: 

[source]
----
clj -X:build
----

Override a parameter, like `:version`:

[source]
----
clj -X:build '[:params :build/version]' '"2.2.2"'
----

== Creating new tasks

Tasks are functions that take the following form:

[source,clojure]
----
(defn a-task [basis params])

  basis - the basis created by build params
  params - a merged map consisting of shared params and task params
----

Tasks may return a map containing new params to be passed to subsequent tasks.


